export const projectsData = [
	{
		id: '1',
		title: 'Automated Inventory Management System',
		supervisor: 'Dr. John Smith',
		thematic: 'Computer Control & Automation',
	},
	{
		id: '2',
		title: 'E-commerce Website Redesign',
		supervisor: 'Prof. Sarah Johnson',
		thematic: 'Communication Engineering',
	},
	{
		id: '3',
		title: 'Machine Learning for Image Recognition',
		supervisor: 'Dr. Michael Brown',
		thematic: 'Signal Processing',
	},
	{
		id: '4',
		title: 'Mobile App Development for Task Tracking',
		supervisor: 'Prof. David Miller',
		thematic: 'Computer Control & Automation',
	},
	{
		id: '5',
		title: 'Environmental Sustainability Analysis',
		supervisor: 'Dr. Emily Davis',
		thematic: 'Power Engineering',
	},
	{
		id: '6',
		title: 'Social Media Sentiment Analysis',
		supervisor: 'Prof. Susan Lee',
		thematic: 'Signal Processing',
	},
	{
		id: '7',
		title: 'Blockchain-based Supply Chain Tracking',
		supervisor: 'Dr. Richard White',
		thematic: 'Electronics',
	},
	{
		id: '8',
		title: 'Natural Language Processing Chatbot',
		supervisor: 'Prof. Linda Garcia',
		thematic: 'Signal Processing',
	},
	{
		id: '9',
		title: 'Data Visualization Dashboard',
		supervisor: 'Dr. William Anderson',
		thematic: 'Signal Processing',
	},
	{
		id: '10',
		title: 'IoT Smart Home Automation',
		supervisor: 'Prof. Jennifer Clark',
		thematic: 'Electronics',
	},
	{
		id: '11',
		title: 'Augmented Reality Gaming App',
		supervisor: 'Dr. Robert Davis',
		thematic: 'Electronics',
	},
	{
		id: '12',
		title: 'Biomedical Research Data Analysis',
		supervisor: 'Prof. Maria Rodriguez',
		thematic: 'Signal Processing',
	},
	{
		id: '13',
		title: 'Epidemiological Modeling',
		supervisor: 'Dr. Patricia Wilson',
		thematic: 'Power Engineering',
	},
	{
		id: '14',
		title: 'Renewable Energy System Optimization',
		supervisor: 'Prof. Charles Turner',
		thematic: 'Power Engineering',
	},
	{
		id: '15',
		title: 'E-learning Platform Development',
		supervisor: 'Dr. Laura Martinez',
		thematic: 'Computer Control & Automation',
	},
	{
		id: '16',
		title: 'Robotic Process Automation for Finance',
		supervisor: 'Prof. Edward Harris',
		thematic: 'Computer Control & Automation',
	},
	{
		id: '17',
		title: 'Human-Computer Interaction Research',
		supervisor: 'Dr. Carol Adams',
		thematic: 'Electronics',
	},
	{
		id: '18',
		title: 'Wireless Sensor Network Deployment',
		supervisor: 'Prof. Daniel Brown',
		thematic: 'Electronics',
	},
	{
		id: '19',
		title: 'Virtual Reality Healthcare Simulation',
		supervisor: 'Dr. Elizabeth Smith',
		thematic: 'Electronics',
	},
	{
		id: '20',
		title: 'Mobile Health App for Chronic Illness Management',
		supervisor: 'Prof. Jessica Taylor',
		thematic: 'Communication Engineering',
	},
]
